apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u0ktctrwq-nodejs 
  janus-idp.io/tekton: u0ktctrwq-nodejs
  backstage.io/kubernetes-id: u0ktctrwq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u0ktctrwq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml